-- ================================================================
-- LOTTO AZAR RESULTADOS — Setup completo de base de datos
-- Ejecutar este archivo en el SQL Editor del NUEVO proyecto Supabase
-- Incluye: tablas, funciones RPC, políticas RLS y datos iniciales
-- ================================================================

-- ────────────────────────────────────────────────────────────────
-- 01. Admin Auth
-- ────────────────────────────────────────────────────────────────

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.admins (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  email text UNIQUE NOT NULL,
  password_hash text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

INSERT INTO
    public.admins (email, password_hash)
VALUES (
        'whpj6436@gmail.com',
        crypt ('azar1234', gen_salt ('bf'))
    ) ON CONFLICT (email) DO NOTHING;

ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Denegar todo el acceso a usuarios anónimos o no autenticados" ON public.admins;

CREATE POLICY "Denegar todo el acceso a usuarios anónimos o no autenticados" ON public.admins FOR ALL USING (false);

CREATE OR REPLACE FUNCTION public.verify_admin_login(admin_email text, admin_password text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  is_valid boolean;
BEGIN
  SELECT EXISTS (
    SELECT 1
    FROM public.admins
    WHERE email = admin_email
    AND password_hash = crypt(admin_password, password_hash)
  ) INTO is_valid;

  RETURN coalesce(is_valid, false);
END;
$$;

-- ────────────────────────────────────────────────────────────────
-- 02. Pyramid Data
-- ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.pyramid (
  id integer PRIMARY KEY DEFAULT 1,
  data jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT pyramid_id_check CHECK (id = 1)
);

INSERT INTO public.pyramid (id, data)
VALUES (
  1,
  '[
    [0, 8, 0, 3, 2, 0, 2, 6],
    [8, 8, 3, 5, 2, 2, 8],
    [6, 1, 8, 7, 4, 0],
    [7, 9, 5, 1, 4],
    [6, 4, 6, 5],
    [0, 0, 1],
    [0, 1],
    [1]
  ]'::jsonb
)
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.pyramid ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir lectura publica de la piramide" ON public.pyramid;

CREATE POLICY "Permitir lectura publica de la piramide" ON public.pyramid FOR
SELECT USING (true);

DROP POLICY IF EXISTS "Permitir actualizacion solo a administradores" ON public.pyramid;

CREATE POLICY "Permitir actualizacion solo a administradores" ON public.pyramid FOR
UPDATE USING (
    auth.role () = 'authenticated'
);

-- ────────────────────────────────────────────────────────────────
-- 03. Pyramid Update RPC
-- ────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.update_pyramid(new_data jsonb)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.pyramid
  SET data = new_data, updated_at = timezone('utc', now())
  WHERE id = 1;

  RETURN FOUND;
END;
$$;

-- ────────────────────────────────────────────────────────────────
-- 04. Pronósticos
-- ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.pronosticos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hora text NOT NULL,
  loteria text NOT NULL,
  animal text NOT NULL,
  numero integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT pronosticos_hora_unique UNIQUE (hora)
);

ALTER TABLE public.pronosticos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Lectura publica de pronosticos" ON public.pronosticos;

CREATE POLICY "Lectura publica de pronosticos" ON public.pronosticos FOR
SELECT USING (true);

DROP POLICY IF EXISTS "Bloquear escritura directa" ON public.pronosticos;

CREATE OR REPLACE FUNCTION public.upsert_pronostico(
  p_hora text,
  p_loteria text,
  p_animal text,
  p_numero integer
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  result json;
BEGIN
  INSERT INTO public.pronosticos (hora, loteria, animal, numero)
  VALUES (p_hora, p_loteria, p_animal, p_numero)
  ON CONFLICT (hora) DO UPDATE
    SET loteria = EXCLUDED.loteria,
        animal = EXCLUDED.animal,
        numero = EXCLUDED.numero
  RETURNING to_json(pronosticos.*) INTO result;

  RETURN result;
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_pronostico(p_id bigint)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM public.pronosticos WHERE id = p_id;
  RETURN FOUND;
END;
$$;

-- ────────────────────────────────────────────────────────────────
-- 05. Fix Pronosticos RLS + RPC de lectura
-- ────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.get_pronosticos()
RETURNS SETOF public.pronosticos
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY SELECT * FROM public.pronosticos ORDER BY created_at ASC;
END;
$$;

-- ────────────────────────────────────────────────────────────────
-- 06. Sorteos
-- ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.sorteos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  animal text NOT NULL,
  numero integer NOT NULL DEFAULT 0,
  hora text NOT NULL,
  fecha date NOT NULL,
  emoji text NOT NULL DEFAULT '🐾',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT sorteos_fecha_hora_unique UNIQUE (fecha, hora)
);

ALTER TABLE public.sorteos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Lectura publica de sorteos" ON public.sorteos;

CREATE POLICY "Lectura publica de sorteos" ON public.sorteos FOR
SELECT USING (true);

CREATE OR REPLACE FUNCTION public.upsert_sorteo(
  p_animal text,
  p_numero integer,
  p_hora text,
  p_fecha date,
  p_emoji text
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  result json;
BEGIN
  INSERT INTO public.sorteos (animal, numero, hora, fecha, emoji)
  VALUES (p_animal, p_numero, p_hora, p_fecha, p_emoji)
  ON CONFLICT (fecha, hora) DO UPDATE
    SET animal = EXCLUDED.animal,
        numero = EXCLUDED.numero,
        emoji = EXCLUDED.emoji
  RETURNING to_json(sorteos.*) INTO result;

  RETURN result;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_sorteo(
  p_id bigint,
  p_animal text,
  p_numero integer,
  p_hora text,
  p_fecha date,
  p_emoji text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.sorteos
  SET animal = p_animal,
      numero = p_numero,
      hora = p_hora,
      fecha = p_fecha,
      emoji = p_emoji
  WHERE id = p_id;

  RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_sorteo(p_id bigint)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM public.sorteos WHERE id = p_id;
  RETURN FOUND;
END;
$$;

-- ────────────────────────────────────────────────────────────────
-- 07. Bet Config
-- ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.bet_config (
  id integer PRIMARY KEY DEFAULT 1,
  monto_minimo numeric NOT NULL DEFAULT 1,
  monto_maximo numeric NOT NULL DEFAULT 10000,
  multiplicador_normal numeric NOT NULL DEFAULT 70,
  multiplicador_comodin numeric NOT NULL DEFAULT 140,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT bet_config_single_row CHECK (id = 1)
);

INSERT INTO
    public.bet_config (
        id,
        monto_minimo,
        monto_maximo,
        multiplicador_normal,
        multiplicador_comodin
    )
VALUES (1, 1, 10000, 70, 140) ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.bet_config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Lectura publica de bet_config" ON public.bet_config;

CREATE POLICY "Lectura publica de bet_config" ON public.bet_config FOR
SELECT USING (true);

DROP POLICY IF EXISTS "Admin puede escribir bet_config" ON public.bet_config;

CREATE POLICY "Admin puede escribir bet_config" ON public.bet_config FOR ALL USING (true)
WITH
    CHECK (true);

-- ────────────────────────────────────────────────────────────────
-- 08. Probabilidades
-- ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.probabilidades (
    id serial primary key,
    animal text not null,
    emoji text not null default '🐾',
    numero text not null default '?',
    peso integer not null default 10 check (
        peso >= 0
        and peso <= 100
    ),
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

CREATE UNIQUE INDEX IF NOT EXISTS probabilidades_animal_idx ON public.probabilidades (animal);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  new.updated_at = now();
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS trg_probabilidades_updated_at ON public.probabilidades;

CREATE TRIGGER trg_probabilidades_updated_at
  BEFORE UPDATE ON public.probabilidades
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.probabilidades ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_probabilidades" ON public.probabilidades;

CREATE POLICY "public_read_probabilidades" ON public.probabilidades FOR
SELECT USING (true);

DROP POLICY IF EXISTS "admin_write_probabilidades" ON public.probabilidades;

CREATE POLICY "admin_write_probabilidades" ON public.probabilidades FOR ALL USING (
    auth.role () = 'authenticated'
)
WITH
    CHECK (
        auth.role () = 'authenticated'
    );

CREATE OR REPLACE FUNCTION public.upsert_probabilidad(
  p_animal text,
  p_emoji  text,
  p_numero text,
  p_peso   integer,
  p_activo boolean DEFAULT true
) RETURNS public.probabilidades LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_row public.probabilidades;
BEGIN
  INSERT INTO public.probabilidades (animal, emoji, numero, peso, activo)
  VALUES (p_animal, p_emoji, p_numero, p_peso, p_activo)
  ON CONFLICT (animal) DO UPDATE
    SET emoji  = excluded.emoji,
        numero = excluded.numero,
        peso   = excluded.peso,
        activo = excluded.activo
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_probabilidad(p_id integer)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  DELETE FROM public.probabilidades WHERE id = p_id;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.probabilidades LIMIT 1) THEN
    INSERT INTO public.probabilidades (animal, emoji, numero, peso) VALUES
      ('Delfín',         '🐬', '0',   7),
      ('Ballena',        '🐳', '00',  4),
      ('Carnero',        '🐏', '01', 15),
      ('Toro',           '🐂', '02', 12),
      ('Ciempiés',       '🐛', '03',  5),
      ('Alacrán',        '🦂', '04',  6),
      ('León',           '🦁', '05', 18),
      ('Rana',           '🐸', '06', 10),
      ('Perico',         '🦜', '07',  8),
      ('Ratón',          '🐭', '08', 14),
      ('Águila',         '🦅', '09', 20),
      ('Tigre',          '🐯', '10', 22),
      ('Gato',           '🐱', '11', 25),
      ('Caballo',        '🐴', '12', 30),
      ('Mono',           '🐒', '13', 16),
      ('Paloma',         '🕊️', '14', 11),
      ('Zorro',          '🦊', '15',  9),
      ('Oso',            '🐻', '16', 13),
      ('Pavo',           '🦃', '17',  7),
      ('Burro',          '🫏', '18',  6),
      ('Chivo',          '🐐', '19', 10),
      ('Cochino',        '🐷', '20', 12),
      ('Gallo',          '🐓', '21', 15),
      ('Camello',        '🐫', '22',  5),
      ('Cebra',          '🦓', '23',  8),
      ('Iguana',         '🦎', '24',  7),
      ('Gallina',        '🐔', '25', 18),
      ('Vaca',           '🐄', '26', 20),
      ('Perro',          '🐶', '27', 35),
      ('Zamuro',         '🦅', '28',  4),
      ('Elefante',       '🐘', '29', 16),
      ('Caimán',         '🐊', '30',  9),
      ('Lapa',           '🦫', '31',  6),
      ('Ardilla',        '🐿️', '32', 11),
      ('Pescado',        '🐟', '33', 14),
      ('Venado',         '🦌', '34', 12),
      ('Jirafa',         '🦒', '35', 28),
      ('Culebra',        '🐍', '36',  8),
      ('Tortuga',        '🐢', '37',  7),
      ('Búfalo',         '🐃', '38',  9),
      ('Lechuza',        '🦉', '39', 10),
      ('Avispa',         '🐝', '40',  5),
      ('Canguro',        '🦘', '41', 10),
      ('Tucán',          '🐦', '42',  8),
      ('Mariposa',       '🦋', '43',  9),
      ('Chigüire',       '🦫', '44', 10),
      ('Garza',          '🦩', '45',  7),
      ('Puma',           '🐆', '46', 14),
      ('Pavo Real',      '🦚', '47', 11),
      ('Puercoespín',    '🦔', '48',  5),
      ('Pereza',         '🦥', '49',  6),
      ('Canario',        '🐤', '50', 12),
      ('Pelícano',       '🦤', '51',  8),
      ('Pulpo',          '🐙', '52',  7),
      ('Caracol',        '🐌', '53',  5),
      ('Grillo',         '🦗', '54',  4),
      ('Oso Hormiguero', '🐽', '55',  6),
      ('Tiburón',        '🦈', '56', 18),
      ('Pato',           '🦆', '57', 13),
      ('Hormiga',        '🐜', '58',  5),
      ('Pantera',        '🐈‍⬛', '59', 16),
      ('Camaleón',       '🦎', '60',  8),
      ('Panda',          '🐼', '61', 20),
      ('Cachicamo',      '🦔', '62',  7),
      ('Cangrejo',       '🦀', '63',  9),
      ('Gavilán',        '🦅', '64', 12),
      ('Araña',          '🕷️', '65',  7),
      ('Lobo',           '🐺', '66', 15),
      ('Avestruz',       '🦩', '67',  8),
      ('Jaguar',         '🐆', '68', 17),
      ('Conejo',         '🐇', '69', 22),
      ('Bisonte',        '🦬', '70', 10),
      ('Guacamaya',      '🦜', '71', 12),
      ('Gorila',         '🦍', '72', 14),
      ('Hipopótamo',     '🦛', '73', 10),
      ('Guácharo',       '🦇', '74',  6),
      ('Turpial',        '🐦', '75',  8);
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────
-- 09. Carrusel Animales + Storage bucket
-- ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.carrusel_animales (
    id SERIAL PRIMARY KEY,
    nombre TEXT NOT NULL,
    imagen_url TEXT NOT NULL,
    orden INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_carrusel_animales_orden ON public.carrusel_animales (orden ASC);

ALTER TABLE public.carrusel_animales ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Lectura pública carrusel" ON public.carrusel_animales;

CREATE POLICY "Lectura pública carrusel" ON public.carrusel_animales FOR
SELECT USING (true);

DROP POLICY IF EXISTS "Solo autenticados pueden insertar" ON public.carrusel_animales;

CREATE POLICY "Solo autenticados pueden insertar" ON public.carrusel_animales FOR
INSERT
WITH
    CHECK (true);

DROP POLICY IF EXISTS "Solo autenticados pueden eliminar" ON public.carrusel_animales;

CREATE POLICY "Solo autenticados pueden eliminar" ON public.carrusel_animales FOR DELETE USING (true);

-- Crear bucket de Storage para imágenes del carrusel
INSERT INTO
    storage.buckets (id, name, public)
VALUES (
        'carrusel-animales',
        'carrusel-animales',
        true
    ) ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Imágenes carrusel públicas" ON storage.objects;

CREATE POLICY "Imágenes carrusel públicas" ON storage.objects FOR
SELECT USING (
        bucket_id = 'carrusel-animales'
    );

DROP POLICY IF EXISTS "Subir al carrusel" ON storage.objects;

CREATE POLICY "Subir al carrusel" ON storage.objects FOR
INSERT
WITH
    CHECK (
        bucket_id = 'carrusel-animales'
    );

DROP POLICY IF EXISTS "Eliminar del carrusel" ON storage.objects;

CREATE POLICY "Eliminar del carrusel" ON storage.objects FOR DELETE USING (
    bucket_id = 'carrusel-animales'
);

-- ================================================================
-- ✅ Setup completo. Ahora importa tus CSVs en cada tabla desde
--    Table Editor → Insert → Import data from CSV
-- ================================================================